const Data = [
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem illo dolor sapiente repellat consequatur recusandae laudantium perspiciatis numquam saepe, qui vero reprehenderit totam fugiat consectetur blanditiis excepturi modi vel adipisci cumque, distinctio amet nisi provident! Architecto ab, saepe labore ipsum, iure, nam magni distinctio quos expedita non fugiat similique voluptatum?',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem illo dolor sapiente repellat consequatur recusandae laudantium perspiciatis numquam saepe, qui vero reprehenderit totam fugiat consectetur blanditiis excepturi modi vel adipisci cumque, distinctio amet nisi provident! Architecto ab, saepe labore ipsum, iure, nam magni distinctio quos expedita non fugiat similique voluptatum?',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem illo dolor sapiente repellat consequatur recusandae laudantium perspiciatis numquam saepe, qui vero reprehenderit totam fugiat consectetur blanditiis excepturi modi vel adipisci cumque, distinctio amet nisi provident! Architecto ab, saepe labore ipsum, iure, nam magni distinctio quos expedita non fugiat similique voluptatum?',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem illo dolor sapiente repellat consequatur recusandae laudantium perspiciatis numquam saepe, qui vero reprehenderit totam fugiat consectetur blanditiis excepturi modi vel adipisci cumque, distinctio amet nisi provident! Architecto ab, saepe labore ipsum, iure, nam magni distinctio quos expedita non fugiat similique voluptatum?',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem illo dolor sapiente repellat consequatur recusandae laudantium perspiciatis numquam saepe, qui vero reprehenderit totam fugiat consectetur blanditiis excepturi modi vel adipisci cumque, distinctio amet nisi provident! Architecto ab, saepe labore ipsum, iure, nam magni distinctio quos expedita non fugiat similique voluptatum?',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem illo dolor sapiente repellat consequatur recusandae laudantium perspiciatis numquam saepe, qui vero reprehenderit totam fugiat consectetur blanditiis excepturi modi vel adipisci cumque, distinctio amet nisi provident! Architecto ab, saepe labore ipsum, iure, nam magni distinctio quos expedita non fugiat similique voluptatum?',
]

export default Data
